# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Loud & Abrasive"
email: loudandabrasive@protonmail.com
organization: "Loud & Abrasive & Co."
description: > # this means to ignore newlines until "baseurl:"
  Art, Games, Software, and Bulls*** brought to you by Patrick-McVeety-Mill.
  See, sample, download, and support it all here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://loudandabrasive.com"
permalink: ":title"
excerpt_separator: <!--more-->
pagination:
  per_page: 4
  enabled: true
  sort_reverse: true
  permalink: '/page/:num/'
  title: ':title - page :num'

sitemap:
  filename: "/sitemap.xml"
  exclude:
      - "/atom.xml"
      - "/feed.xml"
      - "/feed/index.xml"
  include_posts:
      - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
#  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
